# Generated by Django 4.2.3 on 2023-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_hackathon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
