# Generated by Django 4.2.3 on 2023-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_hackathon_created_alter_hackathon_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
