# Generated by Django 4.2.3 on 2023-07-15 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_hackathon_end_time_alter_hackathon_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 46, 50, 18681)),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 46, 50, 18665)),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 46, 50, 18655)),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 46, 50, 18685)),
        ),
    ]
