# Generated by Django 4.2.3 on 2023-07-15 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_alter_hackathon_created_alter_hackathon_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 49, 57, 200848)),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 49, 57, 200831)),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 49, 57, 200821)),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 49, 57, 200852)),
        ),
    ]
