# Generated by Django 4.2.3 on 2023-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='type_of_submission',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='type_of_submission',
            field=models.PositiveIntegerField(choices=[(0, 'image'), (1, 'file'), (2, 'link')], default=0),
            preserve_default=False,
        ),
    ]
