# Generated by Django 4.2.3 on 2023-07-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_hackathon_background_image_hackathon_hackathon_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='user_id',
        ),
    ]
