# Generated by Django 4.2.3 on 2023-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_remove_submission_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
