# Generated by Django 4.2.3 on 2023-07-15 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_alter_hackathon_created_alter_hackathon_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
