# Generated by Django 4.2.3 on 2023-07-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_submission_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
